function Features() {
    const features = [
      {
              icon: (
                        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#6366f1" strokeWidth="2">
                                  <path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/>
                        </svg>svg>
                      ),
              title: "Real-time alerts",
              description: "Get notified instantly the moment a new review is posted — never miss one again."
      },
      {
              icon: (
                        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#6366f1" strokeWidth="2">
                                  <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/>
                        </svg>svg>
                      ),
              title: "AI-powered replies",
              description: "Respond to any review in one click with smart, personalized suggestions generated by AI."
      },
      {
              icon: (
                        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#6366f1" strokeWidth="2">
                                  <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>
                        </svg>svg>
                      ),
              title: "Request reviews by SMS",
              description: "Automatically ask satisfied customers for a review after each visit. More reviews, less effort."
      }
        ]
      
        return (
              <section id="features" className="py-20 px-6 bg-white">
                    <div className="max-w-4xl mx-auto">
                            <div className="text-center mb-12">
                                      <h2 className="text-2xl font-bold text-gray-900 mb-3 tracking-tight">
                                                  Your reputation, under control
                                      </h2>h2>
                                      <p className="text-gray-400 text-sm">Everything you need. Nothing you don't.</p>p>
                            </div>div>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                              {features.map((feature, index) => (
                            <div key={index} className="rounded-2xl p-6 border" style={{ borderColor: '#f1f5f9', backgroundColor: '#fafafe' }}>
                                          <div className="w-10 h-10 rounded-xl flex items-center justify-center mb-4" style={{ backgroundColor: '#eef2ff' }}>
                                            {feature.icon}
                                          </div>div>
                                          <h3 className="font-semibold text-gray-900 mb-2 text-sm">{feature.title}</h3>h3>
                                          <p className="text-gray-400 text-sm leading-relaxed">{feature.description}</p>p>
                            </div>div>
                          ))}
                            </div>div>
                    </div>div>
              </section>section>
            )
}

export default Features</svg>
