function Features() {
  const features = [
    {
      emoji: "🔔",
      title: "Real-time alerts",
      description: "Get notified instantly on your phone the moment a new review is posted — never miss one again."
    },
    {
      emoji: "🤖",
      title: "AI-powered replies",
      description: "Respond to any review in one click with smart, personalized suggestions generated by AI."
    },
    {
      emoji: "📱",
      title: "Request reviews by SMS",
      description: "Automatically ask satisfied customers for a review after each visit. More reviews, less effort."
    }
  ]

  return (
    <section className="py-20 px-6 bg-white">

      {/* Titre */}
      <h2 className="text-3xl font-bold text-blue-900 text-center mb-4">
        Your reputation, under control
      </h2>
      <p className="text-gray-500 text-center mb-12">
        Everything you need. Nothing you don't.
      </p>

      {/* Cartes */}
      <div className="flex flex-col md:flex-row gap-6 max-w-4xl mx-auto">
        {features.map((feature, index) => (
          <div key={index} className="flex-1 bg-gray-50 rounded-2xl p-8">
            <div className="text-4xl mb-4">{feature.emoji}</div>
            <h3 className="text-blue-900 font-bold text-xl mb-3">{feature.title}</h3>
            <p className="text-gray-500">{feature.description}</p>
          </div>
        ))}
      </div>

    </section>
  )
}

export default Features